// recommendations.jsx — Category Recommendations workflow (Stage 3)

const ActionPill = ({ action }) => {
  const map = {
    ADD: { bg:'#E7F6EC', fg:'#217A4C', border:'#B6E0C4', dot:'#3BB273' },
    DROP: { bg:'#FDECF2', fg:'#B42543', border:'#F1BFC0', dot:'#E74C67' },
    CARRY: { bg:'#ECEEFD', fg:'#2E3FB5', border:'#C5CFF9', dot:'#4259EE' },
  };
  const v = map[action];
  return (
    <span style={{
      display:'inline-flex', alignItems:'center', gap: 5,
      padding:'3px 9px', borderRadius: 4, background: v.bg, border:`1px solid ${v.border}`,
      color: v.fg, fontFamily:'Manrope', fontWeight: 800, fontSize: 11, letterSpacing:'.04em',
    }}>
      <span style={{ width: 5, height: 5, borderRadius: 9999, background: v.dot }}/>
      {action}
    </span>
  );
};

const STATUS_PILLS = {
  pending: { variant:'pending', label:'Pending review' },
  accepted: { variant:'approved', label:'Accepted' },
  modified: { variant:'review', label:'Modified' },
  escalated: { variant:'rejected', label:'Escalated' },
  discretion: { variant:'draft', label:'Your call' },
};

const RecommendationsScreen = ({ onOpenSku }) => {
  const [filter, setFilter] = React.useState('all');
  const [selected, setSelected] = React.useState(new Set());
  const [recState, setRecState] = React.useState(() => {
    const m = {}; RECOMMENDATIONS.forEach(r => m[r.id] = r.status); return m;
  });

  const filtered = RECOMMENDATIONS.filter(r => filter === 'all' || recState[r.id] === filter || (filter === 'discretion' && r.status === 'discretion'));
  const counts = {
    all: RECOMMENDATIONS.length,
    pending: RECOMMENDATIONS.filter(r => recState[r.id]==='pending').length,
    accepted: RECOMMENDATIONS.filter(r => recState[r.id]==='accepted').length,
    modified: RECOMMENDATIONS.filter(r => recState[r.id]==='modified').length,
    escalated: RECOMMENDATIONS.filter(r => recState[r.id]==='escalated').length,
    discretion: RECOMMENDATIONS.filter(r => r.status==='discretion').length,
  };

  const accept = (id) => setRecState(s => ({...s, [id]: 'accepted'}));
  const escalate = (id) => setRecState(s => ({...s, [id]: 'escalated'}));

  const tabs = [
    { id: 'all', label: 'All', count: counts.all },
    { id: 'pending', label: 'Pending', count: counts.pending },
    { id: 'accepted', label: 'Accepted', count: counts.accepted },
    { id: 'modified', label: 'Modified', count: counts.modified },
    { id: 'escalated', label: 'Escalated', count: counts.escalated },
    { id: 'discretion', label: 'Your call (20%)', count: counts.discretion },
  ];

  return (
    <div style={{ display:'flex', flexDirection:'column', minHeight:'100%' }}>
      <div style={{ padding:'18px 20px 0' }}>
        <div style={{ display:'flex', alignItems:'center', gap: 10, fontFamily:'Manrope', fontSize: 11.5, fontWeight: 600, color:'#60697D', marginBottom: 6 }}>
          <span>Assortment Intelligence</span>
          <IconChevronRight size={11}/>
          <span style={{ color:'#1F2B4D' }}>Category Recommendations</span>
          <span style={{ color:'#D9DDE7' }}>·</span>
          <Pill variant="review" size="sm" dot={false}>Stage 3 · Pilot</Pill>
        </div>
        <div style={{ display:'flex', alignItems:'flex-start', gap: 16 }}>
          <div style={{ flex: 1 }}>
            <h2 className="ia" style={{ margin: 0, fontSize: 24, letterSpacing:'-0.01em' }}>PLR-2026-W18 · Tile Pilot</h2>
            <div style={{ fontFamily:'Manrope', fontWeight: 500, fontSize: 13, color:'#60697D', marginTop: 4 }}>
              Generated by D. Rivera (CM) <span style={{color:'#D9DDE7'}}>·</span> Pro-Heavy South cluster <span style={{color:'#D9DDE7'}}>·</span> Review window closes <strong style={{color:'#B42543'}}>Fri 5pm</strong>
            </div>
          </div>
          <div style={{ display:'flex', gap: 8 }}>
            <Button variant="secondary" size="sm" leftIcon={<IconDownload size={13}/>}>Export</Button>
            <Button variant="primary" size="sm" leftIcon={<IconCheck size={13}/>}>Accept all pending ({counts.pending})</Button>
          </div>
        </div>
      </div>

      {/* Workflow tracker */}
      <div style={{ padding:'14px 20px 0' }}>
        <Card padding={0}>
          <div style={{ display:'grid', gridTemplateColumns:'repeat(4, 1fr)', gap: 0 }}>
            {[
              { n: 1, title:'CM Generated', sub:'D. Rivera · Apr 22', done: true },
              { n: 2, title:'AMM Review', sub:'M. Chen · in progress', current: true },
              { n: 3, title:'AMS Acknowledgment', sub:'Pending · 6 stores', upcoming: true },
              { n: 4, title:'Execution Tracking', sub:'PLR-2026-W18 cycle', upcoming: true },
            ].map((s, i, arr) => (
              <div key={i} style={{
                padding:'14px 16px', borderRight: i < arr.length - 1 ? '1px solid #ECEDF3' : 0,
                background: s.current ? '#ECEEFD' : '#fff',
                display:'flex', alignItems:'center', gap: 10,
              }}>
                <div style={{
                  width: 30, height: 30, borderRadius: 9999, flex:'0 0 auto',
                  background: s.done ? '#3BB273' : s.current ? '#4259EE' : '#F5F6FA',
                  color: s.done || s.current ? '#fff' : '#B4BAC7',
                  display:'inline-flex', alignItems:'center', justifyContent:'center',
                  fontFamily:'Manrope', fontWeight: 800, fontSize: 13,
                }}>
                  {s.done ? <IconCheck size={14}/> : s.n}
                </div>
                <div>
                  <div style={{ fontFamily:'Manrope', fontWeight: 700, fontSize: 13, color: s.upcoming ? '#60697D' : '#0D152C' }}>{s.title}</div>
                  <div style={{ fontFamily:'Manrope', fontWeight: 500, fontSize: 11, color:'#60697D' }}>{s.sub}</div>
                </div>
              </div>
            ))}
          </div>
        </Card>
      </div>

      {/* Summary strip */}
      <div style={{ padding:'14px 20px 0', display:'flex', gap: 12 }}>
        <Card padding={12} style={{ flex: 1 }}>
          <div className="ia-kpi-label">Total recommendations</div>
          <div style={{ display:'flex', alignItems:'baseline', gap: 6, marginTop: 4 }}>
            <span className="ia-kpi-value" style={{ fontSize: 22 }}>{counts.all}</span>
            <span style={{ fontFamily:'Manrope', fontSize: 11, color:'#60697D', fontWeight: 600 }}>across 18 stores</span>
          </div>
        </Card>
        <Card padding={12} style={{ flex: 1 }}>
          <div className="ia-kpi-label">ADD recommendations</div>
          <div style={{ display:'flex', alignItems:'baseline', gap: 6, marginTop: 4 }}>
            <span style={{ fontFamily:'Manrope', fontWeight: 800, fontSize: 22, color:'#217A4C' }}>{RECOMMENDATIONS.filter(r=>r.action==='ADD').length}</span>
            <span style={{ fontFamily:'Manrope', fontSize: 11, color:'#60697D', fontWeight: 600 }}>+$348k est.</span>
          </div>
        </Card>
        <Card padding={12} style={{ flex: 1 }}>
          <div className="ia-kpi-label">DROP recommendations</div>
          <div style={{ display:'flex', alignItems:'baseline', gap: 6, marginTop: 4 }}>
            <span style={{ fontFamily:'Manrope', fontWeight: 800, fontSize: 22, color:'#B42543' }}>{RECOMMENDATIONS.filter(r=>r.action==='DROP').length}</span>
            <span style={{ fontFamily:'Manrope', fontSize: 11, color:'#60697D', fontWeight: 600 }}>$102k freed</span>
          </div>
        </Card>
        <Card padding={12} style={{ flex: 1 }}>
          <div className="ia-kpi-label">Avg confidence</div>
          <div style={{ display:'flex', alignItems:'baseline', gap: 6, marginTop: 4 }}>
            <span className="ia-kpi-value" style={{ fontSize: 22 }}>80</span>
            <span style={{ fontFamily:'Manrope', fontSize: 11, color:'#60697D', fontWeight: 600 }}>/ 100</span>
          </div>
        </Card>
        <Card padding={12} style={{ flex: 1 }}>
          <div className="ia-kpi-label">Days remaining</div>
          <div style={{ display:'flex', alignItems:'baseline', gap: 6, marginTop: 4 }}>
            <span style={{ fontFamily:'Manrope', fontWeight: 800, fontSize: 22, color:'#B42543' }}>2</span>
            <span style={{ fontFamily:'Manrope', fontSize: 11, color:'#60697D', fontWeight: 600 }}>review window</span>
          </div>
        </Card>
      </div>

      {/* Tabs + table */}
      <div style={{ padding:'14px 20px 20px' }}>
        <Card padding={0}>
          <Tabs tabs={tabs} value={filter} onChange={setFilter} style={{ padding:'0 12px' }}/>

          {/* Table header */}
          <div style={{
            display:'grid', gridTemplateColumns:'32px 90px 1.6fr 1fr 80px 120px 1fr 200px',
            padding:'10px 14px', borderBottom:'1px solid #ECEDF3', background:'#F8F9FB',
            fontFamily:'Manrope', fontSize: 10.5, fontWeight: 700, color:'#60697D',
            textTransform:'uppercase', letterSpacing:'.06em',
          }}>
            <div></div>
            <div>Action</div>
            <div>SKU</div>
            <div>Reason</div>
            <div style={{textAlign:'right'}}>Confidence</div>
            <div>Status</div>
            <div>AMM Note</div>
            <div style={{textAlign:'right'}}>Decide</div>
          </div>

          {filtered.map((r, i) => {
            const isSel = selected.has(r.id);
            const status = recState[r.id];
            const sp = STATUS_PILLS[status];
            const isPending = status === 'pending';
            return (
              <div key={r.id} style={{
                display:'grid', gridTemplateColumns:'32px 90px 1.6fr 1fr 80px 120px 1fr 200px',
                padding:'12px 14px', borderBottom:'1px solid #F5F6FA',
                alignItems:'center', cursor:'pointer',
                background: isSel ? '#F8FBFF' : status === 'discretion' ? '#FFFEF5' : '#fff',
              }} onClick={() => onOpenSku(SKUS.find(s=>s.id===r.sku))}>
                <div onClick={(e)=>{e.stopPropagation();const ns=new Set(selected);ns.has(r.id)?ns.delete(r.id):ns.add(r.id);setSelected(ns);}}>
                  <div style={{
                    width: 16, height: 16, borderRadius: 4,
                    border: '1.5px solid ' + (isSel ? '#4259EE' : '#D9DDE7'),
                    background: isSel ? '#4259EE' : '#fff',
                    display:'inline-flex', alignItems:'center', justifyContent:'center',
                    color:'#fff',
                  }}>
                    {isSel && <IconCheck size={11}/>}
                  </div>
                </div>
                <div><ActionPill action={r.action}/></div>
                <div style={{ minWidth: 0 }}>
                  <div style={{ fontFamily:'Manrope', fontWeight: 700, fontSize: 13, color:'#0D152C', marginBottom: 2, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}>{r.name}</div>
                  <div style={{ fontFamily:'Manrope', fontSize: 11, color:'#60697D', fontWeight: 500, fontFeatureSettings:'"tnum"' }}>{r.sku} · {r.cat}</div>
                </div>
                <div style={{ fontFamily:'Manrope', fontSize: 12, color:'#1F2B4D', fontWeight: 500, lineHeight: 1.45 }}>{r.reason}</div>
                <div style={{textAlign:'right', display:'flex', justifyContent:'flex-end'}}>
                  <ConfidenceBar score={r.confidence} width={50}/>
                </div>
                <div><Pill variant={sp.variant} size="sm">{sp.label}</Pill></div>
                <div style={{ fontFamily:'Manrope', fontSize: 11.5, color:'#60697D', fontWeight: 500, lineHeight: 1.4 }}>
                  {r.modNote ? (
                    <span style={{ display:'inline-flex', gap: 4, alignItems:'flex-start' }}>
                      <IconMessage size={11} style={{color:'#4259EE', marginTop: 2, flex:'0 0 auto'}}/>
                      <span>{r.modNote}</span>
                    </span>
                  ) : (
                    <span style={{color:'#B4BAC7'}}>—</span>
                  )}
                </div>
                <div style={{ display:'flex', gap: 4, justifyContent:'flex-end' }} onClick={e=>e.stopPropagation()}>
                  {isPending ? (<>
                    <Button variant="success" size="xs" onClick={()=>accept(r.id)}>Accept</Button>
                    <Button variant="secondary" size="xs">Modify</Button>
                    <Button variant="ghost" size="xs" onClick={()=>escalate(r.id)} style={{color:'#B42543'}}>Escalate</Button>
                  </>) : status === 'discretion' ? (
                    <Button variant="primary" size="xs">Make call</Button>
                  ) : (
                    <Button variant="ghost" size="xs">Reopen</Button>
                  )}
                </div>
              </div>
            );
          })}

          <div style={{ padding:'12px 16px', borderTop:'1px solid #ECEDF3', background:'#F8F9FB',
                        display:'flex', alignItems:'center', justifyContent:'space-between' }}>
            <div style={{ fontFamily:'Manrope', fontSize: 12, color:'#60697D', fontWeight: 500 }}>
              Showing {filtered.length} of {RECOMMENDATIONS.length} recommendations · {selected.size} selected
            </div>
            <div style={{ display:'flex', gap: 8 }}>
              <Button variant="secondary" size="sm" disabled={!selected.size}>Bulk modify</Button>
              <Button variant="primary" size="sm" disabled={!selected.size}>Bulk accept ({selected.size})</Button>
            </div>
          </div>
        </Card>
      </div>

      {/* Outcome panel */}
      <div style={{ padding:'0 20px 20px' }}>
        <Card padding={0}>
          <div style={{ padding:'14px 16px', borderBottom:'1px solid #ECEDF3',
                        display:'flex', alignItems:'center', gap: 10 }}>
            <div style={{ width: 28, height: 28, borderRadius: 6, background:'#E7F6EC', color:'#217A4C',
                          display:'inline-flex', alignItems:'center', justifyContent:'center'}}>
              <IconChart size={14}/>
            </div>
            <div style={{ flex: 1 }}>
              <div style={{ fontFamily:'Manrope', fontWeight: 700, fontSize: 13, color:'#0D152C' }}>Model vs. Local — 8-week outcome</div>
              <div style={{ fontFamily:'Manrope', fontWeight: 500, fontSize: 11, color:'#60697D' }}>Tile pilot · Pro-Heavy South · 18 stores</div>
            </div>
            <Pill variant="approved" size="sm">+2.4% sell-through delta</Pill>
          </div>
          <div style={{ display:'grid', gridTemplateColumns:'repeat(3, 1fr)', gap: 0 }}>
            {[
              { name:'Central — Accepted', count:'32 SKUs · 8 stores', st:'+2.4%', rev:'+$184k', trapped:'−$58k', color:'#3BB273', strong: true },
              { name:'Local Override', count:'4 SKUs · 6 stores', st:'+0.6%', rev:'+$28k', trapped:'−$12k', color:'#E1BC29' },
              { name:'Control', count:'0 recs · 4 stores', st:'+0.1%', rev:'baseline', trapped:'baseline', color:'#60697D' },
            ].map((g, i) => (
              <div key={i} style={{ padding: 14, borderRight: i<2 ? '1px solid #ECEDF3' : 0 }}>
                <div style={{ display:'flex', alignItems:'center', gap: 6, marginBottom: 8 }}>
                  <span style={{ width: 8, height: 8, borderRadius: 9999, background: g.color }}/>
                  <span style={{ fontFamily:'Manrope', fontWeight: 700, fontSize: 12, color:'#0D152C' }}>{g.name}</span>
                  {g.strong && <Pill variant="approved" size="sm" dot={false}>Best</Pill>}
                </div>
                <div style={{ fontFamily:'Manrope', fontSize: 10.5, color:'#60697D', fontWeight: 500, marginBottom: 10 }}>{g.count}</div>
                <div style={{ display:'grid', gridTemplateColumns:'repeat(3, 1fr)', gap: 8 }}>
                  <div>
                    <div className="ia-kpi-label" style={{fontSize: 10}}>Sell-through Δ</div>
                    <div style={{ fontFamily:'Manrope', fontWeight: 800, fontSize: 16, color: g.color, fontFeatureSettings:'"tnum"' }}>{g.st}</div>
                  </div>
                  <div>
                    <div className="ia-kpi-label" style={{fontSize: 10}}>Revenue</div>
                    <div style={{ fontFamily:'Manrope', fontWeight: 700, fontSize: 14, color:'#0D152C', fontFeatureSettings:'"tnum"' }}>{g.rev}</div>
                  </div>
                  <div>
                    <div className="ia-kpi-label" style={{fontSize: 10}}>Trapped Δ</div>
                    <div style={{ fontFamily:'Manrope', fontWeight: 700, fontSize: 14, color:'#0D152C', fontFeatureSettings:'"tnum"' }}>{g.trapped}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </Card>
      </div>
    </div>
  );
};

Object.assign(window, { RecommendationsScreen });
